#ifndef __CONFIG_H
#define __CONFIG_H

#if defined TARGET_MAPLE_MINI
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_BIT_0		CLEAR_BIT(GPIOB->CRL, GPIO_CRL_CNF1_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOB->CRL, GPIO_CRL_CNF1_1)
	#define LED1_MODE		SET_BIT(GPIOB->CRL, GPIO_CRL_MODE1)
	#define LED1_ON			(GPIOB->BSRR = GPIO_BSRR_BS1)
	#define LED1_OFF		(GPIOB->BRR = GPIO_BRR_BR1)
	
	#define HAS_DISC_PIN
	#define DISC_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define DISC_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define DISC_BIT_0		SET_BIT(GPIOB->CRH, GPIO_CRH_CNF9_0)
	#define DISC_BIT_1		CLEAR_BIT(GPIOB->CRH, GPIO_CRH_CNF9_1)
	#define DISC_MODE		SET_BIT(GPIOB->CRH, GPIO_CRH_MODE9)
	#define DISC_HIGH		(GPIOB->BSRR = GPIO_BSRR_BS9)
	#define DISC_LOW		(GPIOB->BRR = GPIO_BRR_BR9)

	// Enable the internal pull-down on PB2 pin. By default, PB2
	// is in FLOATING input mode.
	#define PB2_PULLDOWN

#elif defined TARGET_GENERIC_F103_PC13
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPCEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPCEN)
	#define LED1_BIT_0		SET_BIT(GPIOC->CRH, GPIO_CRH_CNF13_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOC->CRH, GPIO_CRH_CNF13_1)
	#define LED1_MODE		SET_BIT(GPIOC->CRH, GPIO_CRH_MODE13)
	#define LED1_OFF		(GPIOC->BSRR = GPIO_BSRR_BS13)
	#define LED1_ON			(GPIOC->BRR = GPIO_BRR_BR13)

	//#define HAS_LED2_PIN //Second LED feature is not currently used.
	#define LED2_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED2_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED2_BIT_0		CLEAR_BIT(GPIOB->CRL, GPIO_CRL_CNF1_0)
	#define LED2_BIT_1		CLEAR_BIT(GPIOB->CRL, GPIO_CRL_CNF1_1)
	#define LED2_MODE		SET_BIT(GPIOB->CRL, GPIO_CRL_MODE1)
	#define LED2_ON			(GPIOB->BSRR = GPIO_BSRR_BS1)
	#define LED2_OFF		(GPIOB->BRR = GPIO_BRR_BR1)

	//#define PB2_PULLDOWN

#elif defined TARGET_GENERIC_F103_PD2
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPDEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPDEN)
	#define LED1_BIT_0		SET_BIT(GPIOD->CRL, GPIO_CRL_CNF2_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOD->CRL, GPIO_CRL_CNF2_1)
	#define LED1_MODE		SET_BIT(GPIOD->CRL, GPIO_CRL_MODE2)
	#define LED1_OFF		(GPIOD->BSRR = GPIO_BSRR_BS2)
	#define LED1_ON			(GPIOD->BRR = GPIO_BRR_BR2)

#elif defined TARGET_GENERIC_F103_PD1
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPDEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPDEN)
	#define LED1_BIT_0		SET_BIT(GPIOD->CRL, GPIO_CRL_CNF1_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOD->CRL, GPIO_CRL_CNF1_1)
	#define LED1_MODE		SET_BIT(GPIOD->CRL, GPIO_CRL_MODE1)
	#define LED1_OFF		(GPIOD->BSRR = GPIO_BSRR_BS1)
	#define LED1_ON			(GPIOD->BRR = GPIO_BRR_BR1)

#elif defined TARGET_GENERIC_F103_PA1
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPAEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPAEN)
	#define LED1_BIT_0		SET_BIT(GPIOA->CRL, GPIO_CRL_CNF1_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOA->CRL, GPIO_CRL_CNF1_1)
	#define LED1_MODE		SET_BIT(GPIOA->CRL, GPIO_CRL_MODE1)
	#define LED1_OFF		(GPIOA->BSRR = GPIO_BSRR_BS1)
	#define LED1_ON			(GPIOA->BRR = GPIO_BRR_BR1)

#elif defined TARGET_GENERIC_F103_PB9
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_BIT_0		SET_BIT(GPIOB->CRH, GPIO_CRH_CNF9_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOB->CRH, GPIO_CRH_CNF9_1)
	#define LED1_MODE		SET_BIT(GPIOB->CRH, GPIO_CRH_MODE9)
	#define LED1_OFF		(GPIOB->BSRR = GPIO_BSRR_BS9)
	#define LED1_ON			(GPIOB->BRR = GPIO_BRR_BR9)

#elif defined TARGET_GENERIC_F103_PE2
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPEEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPEEN)
	#define LED1_BIT_0		SET_BIT(GPIOE->CRL, GPIO_CRL_CNF2_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOE->CRL, GPIO_CRL_CNF2_1)
	#define LED1_MODE		SET_BIT(GPIOE->CRL, GPIO_CRL_MODE2)
	#define LED1_OFF		(GPIOE->BSRR = GPIO_BSRR_BS2)
	#define LED1_ON			(GPIOE->BRR = GPIO_BRR_BR2)

#elif defined TARGET_GENERIC_F103_PA9
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPAEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPAEN)
	#define LED1_BIT_0		SET_BIT(GPIOA->CRH, GPIO_CRH_CNF9_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOA->CRH, GPIO_CRH_CNF9_1)
	#define LED1_MODE		SET_BIT(GPIOA->CRH, GPIO_CRH_MODE9)
	#define LED1_OFF		(GPIOA->BSRR = GPIO_BSRR_BS9)
	#define LED1_ON			(GPIOA->BRR = GPIO_BRR_BR9)

#elif defined TARGET_GENERIC_F103_PE5
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPEEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPEEN)
	#define LED1_BIT_0		SET_BIT(GPIOE->CRL, GPIO_CRL_CNF5_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOE->CRL, GPIO_CRL_CNF5_1)
	#define LED1_MODE		SET_BIT(GPIOE->CRL, GPIO_CRL_MODE5)
	#define LED1_OFF		(GPIOE->BSRR = GPIO_BSRR_BS5)
	#define LED1_ON			(GPIOE->BRR = GPIO_BRR_BR5)

#elif defined TARGET_GENERIC_F103_PB7
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_BIT_0		SET_BIT(GPIOB->CRL, GPIO_CRL_CNF7_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOB->CRL, GPIO_CRL_CNF7_1)
	#define LED1_MODE		SET_BIT(GPIOB->CRL, GPIO_CRL_MODE7)
	#define LED1_OFF		(GPIOB->BSRR = GPIO_BSRR_BS7)
	#define LED1_ON			(GPIOB->BRR = GPIO_BRR_BR7)

#elif defined TARGET_GENERIC_F103_PB0
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_BIT_0		SET_BIT(GPIOB->CRL, GPIO_CRL_CNF0_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOB->CRL, GPIO_CRL_CNF0_1)
	#define LED1_MODE		SET_BIT(GPIOB->CRL, GPIO_CRL_MODE0)
	#define LED1_OFF		(GPIOB->BSRR = GPIO_BSRR_BS0)
	#define LED1_ON			(GPIOB->BRR = GPIO_BRR_BR0)

#elif defined TARGET_GENERIC_F103_PB12
	#define HAS_LED1_PIN
	#define LED1_CLOCK_EN		SET_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_CLOCK_DIS		CLEAR_BIT(RCC->APB2ENR, RCC_APB2ENR_IOPBEN)
	#define LED1_BIT_0		SET_BIT(GPIOB->CRH, GPIO_CRH_CNF12_0)
	#define LED1_BIT_1		CLEAR_BIT(GPIOB->CRH, GPIO_CRH_CNF12_1)
	#define LED1_MODE		SET_BIT(GPIOB->CRH, GPIO_CRH_MODE12)
	#define LED1_OFF		(GPIOB->BSRR = GPIO_BSRR_BS12)
	#define LED1_ON			(GPIOB->BRR = GPIO_BRR_BR12)
#else
	#error "No config for this target"
#endif

#endif
